name: PixiaBills

options:
  deploymentTarget:
    iOS: "15.0"
  createIntermediateGroups: true

settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.pixia.bills
    SWIFT_VERSION: "5.9"
    GENERATE_INFOPLIST_FILE: YES
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 0.1.1
    INFOPLIST_KEY_CFBundleDisplayName: pixia-bills
    INFOPLIST_KEY_CFBundleShortVersionString: 0.1.1
    INFOPLIST_KEY_CFBundleVersion: 1
    INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
    INFOPLIST_KEY_UILaunchScreen_Generation: true
    INFOPLIST_KEY_UIRequiresFullScreen: NO
    TARGETED_DEVICE_FAMILY: "1,2"

targets:
  PixiaBills:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: PixiaBills
    settings:
      base:
        PRODUCT_NAME: PixiaBills
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    scheme:
      gatherCoverageData: false
